package model

type CardBrand string

const (
	CardBrand_AMEX             CardBrand = "AMEX"
	CardBrand_BC               CardBrand = "BC"
	CardBrand_CARNET           CardBrand = "CARNET"
	CardBrand_CARTES_BANCAIRES CardBrand = "CARTES_BANCAIRES"
	CardBrand_CITI             CardBrand = "CITI"
	CardBrand_CUP              CardBrand = "CUP"
	CardBrand_DINERS           CardBrand = "DINERS"
	CardBrand_DISCOVER         CardBrand = "DISCOVER"
	CardBrand_ELO              CardBrand = "ELO"
	CardBrand_GWANGJUBANK      CardBrand = "GWANGJUBANK"
	CardBrand_HIPERCARD        CardBrand = "HIPERCARD"
	CardBrand_HYUNDAI          CardBrand = "HYUNDAI"
	CardBrand_IBK_BC           CardBrand = "IBK_BC"
	CardBrand_JCB              CardBrand = "JCB"
	CardBrand_JEJUBANK         CardBrand = "JEJUBANK"
	CardBrand_JEONBUKBANK      CardBrand = "JEONBUKBANK"
	CardBrand_KAKAOBANK        CardBrand = "KAKAOBANK"
	CardBrand_KBANK            CardBrand = "KBANK"
	CardBrand_KDBBANK          CardBrand = "KDBBANK"
	CardBrand_KEBHANA          CardBrand = "KEBHANA"
	CardBrand_KOOKMIN          CardBrand = "KOOKMIN"
	CardBrand_LOTTE            CardBrand = "LOTTE"
	CardBrand_MAESTRO          CardBrand = "MAESTRO"
	CardBrand_MASTERCARD       CardBrand = "MASTERCARD"
	CardBrand_MIR              CardBrand = "MIR"
	CardBrand_NONGHYUP         CardBrand = "NONGHYUP"
	CardBrand_POST             CardBrand = "POST"
	CardBrand_SAEMAUL          CardBrand = "SAEMAUL"
	CardBrand_SAMSUNG          CardBrand = "SAMSUNG"
	CardBrand_SAVINGBANK       CardBrand = "SAVINGBANK"
	CardBrand_SHINHAN          CardBrand = "SHINHAN"
	CardBrand_SHINHYEOP        CardBrand = "SHINHYEOP"
	CardBrand_SUHYEOP          CardBrand = "SUHYEOP"
	CardBrand_TOSSBANK         CardBrand = "TOSSBANK"
	CardBrand_TROY             CardBrand = "TROY"
	CardBrand_VISA             CardBrand = "VISA"
	CardBrand_WOORI            CardBrand = "WOORI"
)
