package model

type CustomerBelongsTo string

const (
	CustomerBelongsTo_ALIPAY_CN                       CustomerBelongsTo = "ALIPAY_CN"
	CustomerBelongsTo_ALIPAY_HK                       CustomerBelongsTo = "ALIPAY_HK"
	CustomerBelongsTo_MPAY                            CustomerBelongsTo = "MPAY"
	CustomerBelongsTo_DANA                            CustomerBelongsTo = "DANA"
	CustomerBelongsTo_PAYPAY                          CustomerBelongsTo = "PAYPAY"
	CustomerBelongsTo_BOOST                           CustomerBelongsTo = "BOOST"
	CustomerBelongsTo_TNG                             CustomerBelongsTo = "TNG"
	CustomerBelongsTo_GRABPAY_MY                      CustomerBelongsTo = "GRABPAY_MY"
	CustomerBelongsTo_HIPAY                           CustomerBelongsTo = "HIPAY"
	CustomerBelongsTo_GCASH                           CustomerBelongsTo = "GCASH"
	CustomerBelongsTo_MAYA                            CustomerBelongsTo = "MAYA"
	CustomerBelongsTo_GRABPAY_PH                      CustomerBelongsTo = "GRABPAY_PH"
	CustomerBelongsTo_GRABPAY_SG                      CustomerBelongsTo = "GRABPAY_SG"
	CustomerBelongsTo_KAKAOPAY                        CustomerBelongsTo = "KAKAOPAY"
	CustomerBelongsTo_NAVERPAY                        CustomerBelongsTo = "NAVERPAY"
	CustomerBelongsTo_TOSSPAY                         CustomerBelongsTo = "TOSSPAY"
	CustomerBelongsTo_RABBIT_LINE_PAY                 CustomerBelongsTo = "RABBIT_LINE_PAY"
	CustomerBelongsTo_TRUEMONEY                       CustomerBelongsTo = "TRUEMONEY"
	CustomerBelongsTo_KPLUS                           CustomerBelongsTo = "KPLUS"
	CustomerBelongsTo_DIRECT_DEBIT_SIAMCOMMERCIALBANK CustomerBelongsTo = "DIRECT_DEBIT_SIAMCOMMERCIALBANK"
	CustomerBelongsTo_DIRECT_DEBIT_KRUNGTHAIBANK      CustomerBelongsTo = "DIRECT_DEBIT_KRUNGTHAIBANK"
	CustomerBelongsTo_ACH_DIRECT_DEBIT                CustomerBelongsTo = "ACH_DIRECT_DEBIT"
	CustomerBelongsTo_ZALOPAY                         CustomerBelongsTo = "ZALOPAY"
	CustomerBelongsTo_MOMO                            CustomerBelongsTo = "MOMO"
	CustomerBelongsTo_VIETTELMONEY                    CustomerBelongsTo = "VIETTELMONEY"
	CustomerBelongsTo_JKOPAY                          CustomerBelongsTo = "JKOPAY"
	CustomerBelongsTo_BKASH                           CustomerBelongsTo = "BKASH"
	CustomerBelongsTo_EASYPAISA                       CustomerBelongsTo = "EASYPAISA"
	CustomerBelongsTo_DIRECTDEBIT_YAPILY              CustomerBelongsTo = "DIRECTDEBIT_YAPILY"
	CustomerBelongsTo_ANTIM_BIZ_ACCOUNT               CustomerBelongsTo = "ANTIM_BIZ_ACCOUNT"
)
