package model

type DisableReasonType string

const (
	PAYMENT_ACCOUNT_NOT_AVAILABLE DisableReasonType = "PAYMENT_ACCOUNT_NOT_AVAILABLE"
	EXCEED_CHANNEL_LIMIT_RULE     DisableReasonType = "EXCEED_CHANNEL_LIMIT_RULE"
	SERVICE_DEGRADE               DisableReasonType = "SERVICE_DEGRADE"
	CHANNEL_NOT_SUPPORT_CURRENCY  DisableReasonType = "CHANNEL_NOT_SUPPORT_CURRENCY"
	CHANNEL_DISABLE               DisableReasonType = "CHANNEL_DISABLE"
	CHANNEL_NOT_IN_SERVICE_TIME   DisableReasonType = "CHANNEL_NOT_IN_SERVICE_TIME"
	QUERY_IPP_INFO_FAILED         DisableReasonType = "QUERY_IPP_INFO_FAILED"
	LIMIT_CENTER_ACCESS_FAIL      DisableReasonType = "LIMIT_CENTER_ACCESS_FAIL"
	CURRENT_CHANNEL_NOT_EXIST     DisableReasonType = "CURRENT_CHANNEL_NOT_EXIST"
)
